### ISSUE TITLE
Relation to Heat Kernel Signature (HKS)

### ISSUE THREAD

**Issue by vadimkantorov** [Ya-Wei0/HyperbolicDiffusionDistance#1]
Hi!

Am I right that HDD scales eigenvalues `eigval[i]` as `pow(eigval[i], 2^-t)` and HKS scales eigenvalues `exp(eigval[i] * (-t))`? Any intuition what should be the difference conceptully? When one is better than the other? For HKS also tries to capture multi-scale behavior, right?

For eigval[i] == 3:
<img width="597" alt="image" src="https://github.com/Ya-Wei0/HyperbolicDiffusionDistance/assets/1041752/6e271f73-0b34-4c86-86ca-070c786c5fe2">

For eigval[i] == 0.3:
<img width="531" alt="image" src="https://github.com/Ya-Wei0/HyperbolicDiffusionDistance/assets/1041752/f8c3f341-22d5-4f4f-9cf6-08b480481dfd">

**Comment by ghost** [comment]
Hi! Thanks for your interest in our work!

In the limit case ($n\rightarrow\infty$ and $\epsilon\rightarrow 0$), the diffusion operator $\mathbf{P}$ converges to the Neumann heat kernel of the underlying manifold $\mathbf{H} = exp(-\Delta)$. Taking the view from $\Delta$, both HKS and our HDE/HDD scale the eigenvalues by $exp(-t)$. However, when parametrizing $t$, we take it in a dyadic scale, i.e., $exp(-2^{-k})$, such that $0 < t=2^{-k}\leq 1$, and in HKS, $t\in\mathbb{R}_+$. Their multi-scales behave in different ways. In addition, when looking at the multi-scale heat kernel, our method is tackling $\mathbf{H}_t(x,y) \in \mathbb{R}^n$ for each point x into a hyperbolic space, whereas HKS is targeting $\mathbf{H}_t(x,x) \in \mathbb{R}$.
Our HDE/HDE is specifically for representing a hierarchal graph or data (negative-curved manifold) and recovering the underlying distance. It is tightly related to heat kernel, yet different than the HKS (in terms of construction).
